export const LOAD_CUSTOMERS_REQUEST = 'LOAD_CUSTOMERS_REQUEST';
export const LOAD_CUSTOMERS_SECCESS = 'LOAD_CUSTOMERS_SECCESS';
export const LOAD_CUSTOMERS_FAIL = 'LOAD_CUSTOMERS_FAIL';

export const UPDATE_CUSTOMER_REQUEST = 'UPDATE_CUSTOMER_REQUEST';
export const UPDATE_CUSTOMER_SECCESS = 'UPDATE_CUSTOMER_SECCESS';
export const UPDATE_CUSTOMER_FAIL = 'UPDATE_CUSTOMER_FAIL';

export const ADD_CUSTOMER_REQUEST = 'ADD_CUSTOMER_REQUEST';
export const ADD_CUSTOMER_SECCESS = 'ADD_CUSTOMER_SECCESS';
export const ADD_CUSTOMER_FAIL = 'ADD_CUSTOMER_FAIL';

export const DELETE_CUSTOMER_REQUEST = 'DELETE_CUSTOMER_REQUEST';
export const DELETE_CUSTOMER_SECCESS = 'DELETE_CUSTOMER_SECCESS';
export const DELETE_CUSTOMER_FAIL = 'DELETE_CUSTOMER_FAIL';

export const SUBMIT_CUSTOMER_FAIL = 'SUBMIT_CUSTOMER_FAIL';