export const LOAD_PRODUCTS_REQUEST = 'LOAD_PRODUCTS_REQUEST';
export const LOAD_PRODUCTS_SECCESS = 'LOAD_PRODUCTS_SECCESS';
export const LOAD_PRODUCTS_FAIL = 'LOAD_PRODUCTS_FAIL';

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SECCESS = 'UPDATE_PRODUCT_SECCESS';
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL';

export const UPDATE_PRODUCT_QUANTITY_REQUEST = 'UPDATE_PRODUCT_QUANTITY_REQUEST';
export const UPDATE_PRODUCT_QUANTITY_SECCESS = 'UPDATE_PRODUCT_QUANTITY_SECCESS';
export const UPDATE_PRODUCT_QUANTITY_FAIL = 'UPDATE_PRODUCT_QUANTITY_FAIL';

export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_SECCESS = 'ADD_PRODUCT_SECCESS';
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SECCESS = 'DELETE_PRODUCT_SECCESS';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';

export const SUBMIT_PRODUCT_FAIL = 'SUBMIT_PRODUCT_FAIL';