

export const LOAD_PURCHASES_REQUEST = 'LOAD_PURCHASES_REQUEST';
export const LOAD_PURCHASES_SECCESS = 'LOAD_PURCHASES_SECCESS';
export const LOAD_PURCHASES_FAIL = 'LOAD_PURCHASES_FAIL';

export const ADD_PURCHASE_REQUEST = 'ADD_PURCHASE_REQUEST';
export const ADD_PURCHASE_SECCESS = 'ADD_PURCHASE_SECCESS';
export const ADD_PURCHASE_FAIL = 'ADD_PURCHASE_FAIL';

export const DELETE_PURCHASE_REQUEST = 'DELETE_PURCHASE_REQUEST';
export const DELETE_PURCHASE_SECCESS = 'DELETE_PURCHASE_SECCESS';
export const DELETE_PURCHASE_FAIL = 'DELETE_PURCHASE_FAIL';

export const SUBMIT_PURCHASE_FAIL = 'SUBMIT_PURCHASE_FAIL';